### ISSUE TITLE
learner 在学习过程当中，有个问题。

### ISSUE THREAD

**Issue by chenld** [luohaha/MyPaxos#1]
learner 在学习过程当中，				
```
// 当learner学习成功时，让accepter也去同步这个状态
this.accepter.getAcceptedValue().put(instance, k);
```
是否都要赋值，或许自己accepter 已经接受了值，这样不就是覆盖，类似于把值重新覆盖了呀。

**Comment by luohaha** [comment]
@chenld 实在不好意思，不知道为啥，github这边没有给我发通知，导致我现在才看到您提的issue。。实在是不好意思。

确实是会覆盖accepter接受的值，因为accepter接受的value不一定是通过多数同意的value，但是learner学习得到的value却是已经通过多数同意的value，所以以learner为准。
