### ISSUE TITLE
multi-paxos 优化 有逻辑错误

### ISSUE THREAD

**Issue by bruan** [luohaha/MyPaxos#3]
A B C三个节点，一开始通过A节点来提交，中间没有竞争发生，最终A提交的值被确定并且在A的proposer中的isLastSumbitSucc设置成true，紧接着，A发生分区（没有crash，只是网络波动），分区的这段时间内，通过B来提交，由于多数派存活，B提交的值是可以被确定的，B的值被确定后，A从分区中恢复过来，并且还来不及向其他节点学习最新的B提交的值，此时A又有新的值要提交了，由于刚才设置了isLastSumbitSucc，所以prepare阶段被跳过，接着发生了悲剧A提交的值被确定了（跟B提交的是同一个instanceID）。

**Comment by luohaha** [comment]
感谢您提的issue，但是我在仔细考虑后，先说下我的观点。

因为，根据您的假设，A发生分区后，B过来提交。b的ballot的id是从1开始的，但是第一轮肯定会失败（因为，之前a在连续提交成功的时候，会去提前prepare，accepter接受了新instance的ballot为1，也就是优化所做的事），所以进入第二轮的prepare阶段，把ballot提升为2，然后成功。
接着，A从分区中恢复过来，因为isLastSumbitSucc为true，直接进入accept阶段，但是发现此时多数accepter的ballot已经变成2了，不再是1了，所以accept阶段会失败，不会出现您说的情况。

以上是我的看法。

**Comment by bruan** [comment]
恩，没有错，我是分析错了！
